name: Deploy V2Ray via Cloudflare Tunnel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set permission
        run: chmod +x start.sh

      - name: Run script
        run: ./start.sh
